export const SUPPORTED_BRANDS = [
    'Rolex',
    'Patek Philippe',
    'Audemars Piguet',
    'Richard Mille',
    'Vacheron Constantin',
    'A. Lange & Söhne',
    'F.P. Journe',
    'Cartier',
    'Omega',
    'Panerai',
    'IWC Schaffhausen',
    'Jaeger-LeCoultre',
    'Hublot',
    'Breitling',
    'Tudor',
    'Montres Breguet',
    'Piaget',
    'Blancpain',
    'Girard-Perregaux',
] as const;
